In [9]:
import pandas as pd

data = pd.Series(list(range(10, 1001)))
display(data)

0        10
1        11
2        12
3        13
4        14
       ...
986     996
987     997
988     998
989     999
990    1000
Length: 991, dtype: int64

In [8]:
print(data.loc[10] + data.loc[23] - data.loc[245] + data.iloc[122])

-70

In [13]:
! ls -la ../data/data_sf.xls

-rw-r--r-- 1 501 dialout 2055796 Nov  6 17:04 ../data/data_sf.xls

In [16]:
football = pd.read_csv('../data/data_sf.xls')

In [18]:
display(football.tail(6))

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
12891,13120,D. Walsh,18,Republic of Ireland,Waterford FC,60000,1000,RB,22,23,...,38,43,44,47,53,9,10,9,11,13
12892,13121,J. Lundstram,19,England,Crewe Alexandra,1100000,1000,CM,34,38,...,43,45,40,48,47,10,13,7,8,9
12893,13122,N. Christoffersson,19,Sweden,Trelleborgs FF,60000,1000,ST,23,52,...,43,42,22,15,19,10,9,9,5,12
12894,13123,B. Worman,16,England,Cambridge United,60000,1000,ST,25,40,...,55,41,32,13,11,6,5,10,6,13
12895,13124,D. Walker-Rice,17,England,Tranmere Rovers,60000,1000,RW,44,50,...,50,46,20,25,27,14,6,14,8,9
12896,13125,G. Nugent,16,England,Tranmere Rovers,60000,1000,CM,41,34,...,33,43,40,43,50,10,15,9,12,9